setps:
  # 1단계 => docker-compose -f docker-compose.prod.yaml build
  - name: docker/compose:1.29.0
    args:
      - -f
      - docker-compose.prod.yaml
      - build




  # 2단계 => docker-compose -f docker-compose.prod.yaml push
  - name: docker/compose:1.29.0
  args:
    - -f
    - docker-compose.prod.yaml

  
  # 3단계 => kubectl set image deployment/my-backend-02 my-backend02-sha256-1=asia.gcr.io/engaged-proxy-347011/my-backend02:5.3
  - name: gcr.io/cloud-builders/kubectl
    args:
      - set
      - image
      - deployment/my-backend-02
      - my-backend02-sha256-1=asia.gcr.io/engaged-proxy-347011/my-backend02:5.3
    env:
      - CLOUDSDK_COMPUTE=asia-northeast3
      - CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-02-1
  