console.log(1 + "1")
console.log(1 - "1")
console.log("1" + "1")
console.log(1 * "1")
console.log(3 * "A")
console.log(1 + 1 + "1")
console.log('1' + 1 + 1)
console.log("11" + 1)
console.log("11" - 1)
console.log("홍" + "길동")
console.log(20 === "20")
console.log(20 == "ex20")
console.log(!true)